<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
			->prependStylesheet($this->basePath('datatables/css/jquery.dataTables.min.css'))
			->prependStylesheet($this->basePath('font-awesome/css/font-awesome.css'))
			->prependStylesheet($this->basePath('css/gijgo.min.css'))
        ?> 
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
				      
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
			</div>
        </nav>
		<!-- Scripts -->
        <?= $this->inlineScript()
		    ->appendFile($this->basePath('js/jquery-3.3.1.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
			->appendFile($this->basePath('dataTables/js/jquery.dataTables.min.js'))
			->appendFile($this->basePath('dataTables/js/dataTables.bootstrap.min.js'))
			->appendFile($this->basePath('js/gijgo.min.js'))
		?>
        <div class="container" style="background-color: grey;">
		
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
    </body>
</html>
